# Generated by Django 4.2.30 on 2026-05-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("link", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="ShortenedUrl",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("short_link", models.CharField()),
                (
                    "url",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortened_urls",
                        to="shortener.url",
                    ),
                ),
            ],
        ),
    ]
