# Generated by Django 4.2.30 on 2026-05-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="url",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
