# Generated by Django 4.2.30 on 2026-05-04 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_alter_shortenedurl_id_alter_url_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="last_accessed",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
