# Generated by Django 4.2.30 on 2026-05-04 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_shortenedurl_last_accessed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="link",
            new_name="main_link",
        ),
        migrations.AddField(
            model_name="url",
            name="last_accessed",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="url",
            name="short_link",
            field=models.CharField(blank=True),
        ),
        migrations.DeleteModel(
            name="ShortenedUrl",
        ),
    ]
